# Orchestra user
ORCHESTRA_USER=$USER
ORCHESTRA_UID=$UID
ORCHESTRA_GID=$(id -g $USER)

# Docker
DOCKER_GID=$(getent group docker | cut -d: -f3)

# Postgresql database
POSTGRESQL_DB=orchestra
POSTGRESQL_USER=orchestra
POSTGRESQL_PASSWORD=orchestra
POSTGRESQL_HOSTNAME=localhost

# Redis server
REDIS_HOSTNAME=localhost

# Flask 
FLASK_APP=orchestra.webservice
FLASK_ENV=dev
FLASK_DEBUG=0
FLASK_HOST=0.0.0.0
FLASK_PORT=5000

# For debug
#echo "ORCHESTRA_USER: $ORCHESTRA_USER"
#echo "ORCHESTRA_UID: $ORCHESTRA_UID"
#echo "ORCHESTRA_GID: $ORCHESTRA_GID"
#echo ""
#echo "DOCKER_GID: $DOCKER_GID"
#echo ""
#echo "POSTGRESQL_USER: $POSTGRESQL_USER" 
#echo "POSTGRESQL_PASSWORD: $POSTGRESQL_PASSWORD"
#echo "POSTGRESQL_HOSTNAME: $POSTGRESQL_HOSTNAME"
#echo "POSTGRESQL_DB: $POSTGRESQL_DB"
#echo ""
#echo "REDIS_HOSTNAME: $REDIS_HOSTNAME"
#echo ""
#echo "FLASK_APP: $FLASK_APP"
#echo "FLASK_ENV: $FLASK_ENV"
#echo "FLASK_DEBUG: $FLASK_DEBUG"
