version: "3"
services:
  redis:
    image: redislabs/redismod
    restart: unless-stopped
  
  postgresql:
    image: postgres
    restart: unless-stopped
    #hostname: orchestra_db
    env_file:
      - ../orchestra_env.sh
    environment:
      - POSTGRES_USER=orchestra
      - POSTGRES_PASSWORD=orchestra
      - POSTGRES_DB=orchestra
    volumes:
      - /var/lib/orchestra/data:/var/lib/postgresql/data

    
  orchestra:
    build:
      context: build_orchestra
      dockerfile: Dockerfile
      args:
        ORCHESTRA_USER:
        ORCHESTRA_UID:
        ORCHESTRA_GID:
        DOCKER_GID:
        FLASK_PORT:
    privileged: true
    env_file:
      - ../orchestra_env.sh
    environment:
      - ORCHESTRA_USER=orchestra
      - POSTGRES_USER=orchestra
      - POSTGRES_PASSWORD=orchestra
      - POSTGRES_DB=orchestra
      - POSTGRES_HOSTNAME=postgresql
      - REDIS_HOSTNAME=redis

    ports:
      - "5000:5000"
    volumes:
      - /var/lib/orchestra:/var/lib/orchestra
      - /var/run/docker.sock:/var/run/docker.sock
