version: "3"
services:
  orchestra_redis:
    image: redislabs/redismod
    restart: unless-stopped
  
  orchestra_db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: orchestra
      POSTGRES_PASSWORD: orchestra
      POSTGRES_DB: orchestra
    volumes:
      - /var/lib/orchestra/data:/var/lib/postgresql/data

    
  orchestra:
    build:
      context: build_orchestra
      dockerfile: Dockerfile
      args:
        ORCHESTRA_USER:
        ORCHESTRA_UID:
        ORCHESTRA_GID:
        DOCKER_GID:
    privileged: true
    environment:
      - ORCHESTRA_UID
    ports:
      - "5000:5000"
    volumes:
      - /var/lib/orchestra:/var/lib/orchestra
      - /var/run/docker.sock:/var/run/docker.sock
